### ISSUE TITLE
Bug: D (blue dot) and E (erase under mouse) (SumatraPDF position notification parsing)

### ISSUE THREAD

**Issue by GitHubRulesOK** [nod5/HighlightJump#6] opened 2020-02-13 02:15 UTC
I can use most key based commands except D and E
which seem to commonly use the measure feature, any ideas why ?
SumatraPDF 3.2.12134 x64 portable on win10x64
AHK U32 & U64 1.1.32.00 portable
Is either app in portable mode the reason ? I don't usually "install" programs

**Comment by nod5** [comment] 2020-02-13 22:32
Do you use a non-english language setting?
Does the issue disappear if you set SumatraPDF to english?

If yes then it is probably the same bug that I have a fix in progress for.

The bug I've tracked down was due to language variation in the postion notification text (`m` shortcut in SumatraPDF). My code used a regex pattern that used the colon `:` in the string `Cursor position:` in that notification. But some translations e.g. [dutch](http://www.apptranslator.org/app/SumatraPDF/nl#) and traditional chinese apparently omit the `:`

**Comment by GitHubRulesOK** [comment] 2020-02-13 22:36
No am not using Mothers tongue I only work with English

**Comment by nod5** [comment] 2020-02-13 23:21
Ok, then there is probably another bug here. I can't reproduce a problem with `D`and `E` and 
`SumatraPDF-prerelease-12134-64.exe` (build date  2020-02-11) in english language. Portable AutoHotkey should not cause any issue either.

When you hold `E` does the cursor change from arrow to cross?

**Comment by GitHubRulesOK** [comment] 2020-02-13 23:52
D flickers M's cross-hairs on/off if held but holding e just shows cross hair then occasionally errors on "71" keypress's without any noticeable result
Old school version  e was not a problem

**Comment by nod5** [comment] 2020-02-13 23:56
>  holding e just shows cross hair then occasionally errors on "71" keypress's without any noticeable result

I'm not sure I understand. Does an error message popup? Can you take a screenshot of it?

**Comment by GitHubRulesOK** [comment] 2020-02-14 00:13
Switched to installed latest 3.2.12137x64 in case instal was needed but no difference
Error has not happened in current time I have tried to see if additionally running Window spy has any info but it does not report any key activity as such (pity) however it reports both Visible text and All Text as /### e.g. it does not show current page is that normal ?

**Comment by GitHubRulesOK** [comment] 2020-02-14 00:40
Puzzling over your language comment I am using UK English locale and keyboard not US in case that may have a bearing, also have **not yet** tested on other machines in case it is hardware specific

**Comment by GitHubRulesOK** [comment] 2020-02-14 01:29
Ok different hardware <strike>different</strike> same problem, Windows 7x64 with touchpad

SumatraPDF 12137x32 or x64 highlight works exactly the same way with AHKU32 or U64 script <strike>does not add any functions when run e.g. a is not highlighting nor 1 storing page location etc. just the help screen options etc. no keyboard response and there is no mouse but touchpad should offer same functions e.g. right click brings up SumatraPDF context</strike> Sorry you need to add to troubleshooting that test file must be on a mapped drive (not \\ share\path)

need to find a hardwire mouse to see if that helps

No adding a hardware mouse made no noticeable difference

**Comment by GitHubRulesOK** [comment] 2020-02-14 01:58
Tending to think it is the rumours that DDE will not work between apps in some cases do both D and E rely on [dde] functions ?

If so, the problem is likely that installed SumatraPDF is not allowed to communicate with AHK via DDE for security reasons

**Comment by nod5** [comment] 2020-02-14 19:00
> Sorry you need to add to troubleshooting that test file must be on a mapped drive (not \ share\path)

Readme updated to say that files with UNC paths are not yet supported.

**Comment by nod5** [comment] 2020-02-14 19:09
New version released that among other things fixes the language bug I found. Try it and see if it may also fix your issue with `D` and `E`.

>  D and E rely on [dde] functions ?

No

> holding e just shows cross hair then occasionally errors on "71" keypress's without any noticeable result

You mentioned this earlier, can you clarify. Was it a popup errormessage from HighlightJump? Or SumatraPDF? Or something else?

**Comment by GitHubRulesOK** [comment] 2020-02-14 20:25
I will try out latest changes
Have not seen message recently may have been for one of the other reasons that a keyboard buffer was exceeded in a short time frame if not processed in timely fashion. I recollect it mentioned something like 1790ms anyway I got the impression it was feedback in an AHK style dialog.

**Comment by nod5** [comment] 2020-02-14 22:03
Ok, sounds like the [#MaxHokeysPerInterval](https://www.autohotkey.com/docs/commands/_MaxHotkeysPerInterval.htm) error message in AutoHotkey. I can't reproduce that here. If you still see the issue in the new version then I will make a smaller diagnostics script for the code used by `D` and `E` to help pin down the cause.

**Comment by GitHubRulesOK** [comment] 2020-02-14 22:14
I am reluctant to cloud by mixing issues however in the interest of looking for a common cause NOTE I do NOT install AHK it is always portable (SumatraPDF IS installed in \Program Files\ thus when running is providing a SERVER for client uses)

**the keys that work are**
 quick jump 1-5
 single color keys A Y R G 
 CTRL Delete
 Win A
 CTRL home and end
also select filter colour Y R G and ctrl shift home and end

**the keys that don't work**
D E
equally, I cant get dot with Rbutton +Mbutton
CTRL PgUp or Pg Dn or in shifted filter combinations dont work

Using mouse shortcuts has sometimes crashed SumatraPDF but lets leave those for now until I can find repeatable pattern.

At this point my best suggestion is some form of breakpoint message box when D or E is selected, I presume it will show a correct value for page and x,y values but don't know what other feedback may be appropriate.

**Comment by GitHubRulesOK** [comment] 2020-02-14 23:38
the message appeared whilst pressing Rbutton too long
![image](https://user-images.githubusercontent.com/12754913/74576518-06b42200-4f83-11ea-976e-3cb266d4f60d.png)

**Comment by GitHubRulesOK** [comment] 2020-02-14 23:49
Out of interest loaded old highlight helper
O will place a blue dot 
CapsLock and mouse will erase under cursor 
!!

**Comment by nod5** [comment] 2020-02-15 20:03
I reproduced an issue with D and E on another PC (a laptop). 
Cause: The old code failed to cover yet another small variation in the SumatraPDF's position notification text between different PCs.

Fixed version uploaded. 15d55ef

I also detected another issue with `E`, On laptops a touchpad setting called palm tracking (palmcheck, palm detection, palm sense) can prevent moving mouse via touchpad while `E` is held.
Workaround: On my test laptop the Synaptic driver settings has a slider for palm tracking. Set the slider to the minimum value. After that that (and the other fix just uploaded) `E` worked.

Because of this touchpad issue I will add one more method for the erase highlights under mouse action.  Alternatives I am considering:
- `E (longpress)` to turn on `mouse erase mode`. Release `E` and move mouse over highlights to erase, no other keys/buttons pressed.  Later press `E` again or `Esc` to exit mouse erase mode.
- Like above but `Ctrl + E` to turn on.
- Bring back `CapsLock`, because modifier keys seem unaffected by palmcheck.

edit:
> CTRL PgUp or Pg Dn or in shifted filter combinations dont work

I have not been able to reproduce that yet. Let us deal with `D` and `E` first.

**Comment by GitHubRulesOK** [comment] 2020-02-15 21:47
Ah yes **Real English** uses th,ous,and.s for decimals but European and International English settings can vary from Local,e to Local.e **also watch out for 1 000.00** other variants

**Comment by GitHubRulesOK** [comment] 2020-02-15 22:08
@nod5 
Ok that now explains why now only those on the top left up to 1,000,1,000 get removed but the majority of others don't my test pages are 2100 wide by 2970 high (=10 pt/mm)
Equally I can put a very very tiny 1mm dot in top left corner
Some files I work with could be up to 85,889.76 pt wide and that's nowhere near the permitted maximum
![image](https://user-images.githubusercontent.com/12754913/74596226-23fcf500-5044-11ea-9a6e-cc4ce0d31c4e.png)

**Comment by GitHubRulesOK** [comment] 2020-02-15 23:06
Without wishing to again cloud this issue of measurment actions in D & E
I noticed that not all the dots requested appeared on the page, and sure enough the page before is littered with dots so seems in part to be related to issue #5 when pages are continuous.

P.S I am going to suggest a dirty fix in that issue

**Comment by GitHubRulesOK** [comment] 2020-02-15 23:29
Just a note to confirm R&M button places dot within the 1000x1000 zone but not outside as expected

PPS the dots are tooo small to erase the cursor keeps missing them 
can you offer an easy pop up to set size ?

**Comment by nod5** [comment] 2020-02-15 23:33
> Ok that now explains why now only those on the top left up to 1,000,1,000 get removed

Ok, so all three `D`, `E` and `Rbutton & Mbutton` work on your PC up to 999 pt position values? 
If yes then that is a step in the right direction at least.

I will next adjust the regex pattern to cover different cases of separator signs for >999 positions. 

> Some files I work with could be up to 85,889.76 pt wide and that's nowhere near the permitted maximum

Do you know what the permitted maximum is? Quick googling didn't find me a definite answer. I suppose this is really two questions: What is permitted maximum in PDF spec? What is the maximum that SumatraPDF can handle? (Third question: Can the "m" notification handle all that SumatraPDF can handle internally?)

In all position value examples mentioned here and that I've seen in SumatraPDF use the position notification has always displayed fractions. Is that true in your experience? I ask because if that is a constant feature then that helps me in crafting the regex pattern.

**Comment by GitHubRulesOK** [comment] 2020-02-15 23:39
I have pps above comment about dot size
off hand I think the max was something stupid like <strike>54 billions</strike> actually 1.7 allows for 15,000,000"x15,000,000" = 1,080,000,000‬ pt square
Adobe recommend a maximum size of 200"x200" it translates to 14,400 pt but users often apply 300dpi 
I have no idea of Sumatra max but don't remember any problems below 999,999,99
Long railway track layouts for Km's or Miles are not uncommon (also think ship and aircraft layouts)

**Comment by nod5** [comment] 2020-02-16 00:53
Thanks. Do you have URLs at hand to the sources for those numbers?

My own personal PDF use is mostly journal articles, books, references works, manuals and similar materials, where the X/Y values are, as far as I've noticed, almost always below 1000 pt . In effect HighlightJump/sumatra_highlight_helper has until now implicitly assumed that kind of use case.

Here is an attempt at handling also cases with larger values and the separator characters `space` and ` ,` and `.`. I put it in a test branch for now.

https://github.com/nod5/HighlightJump/blob/test-position-regex/HighlightJump.ahk

The changes: 4513719

Regex sandbox for the test pattern https://regex101.com/r/QAU3Kt/1/

**Comment by GitHubRulesOK** [comment] 2020-02-16 00:59
Ok will test
one url with a reasonable discussion on practical limit 200" and theoretic limit 381 Km is
https://community.adobe.com/t5/acrobat/is-there-a-page-size-limit-when-exporting-a-pdf-from-indesign/td-p/3811127?page=1

poster artist mess with dpi and CAD users refer to UOR both then mess with the default of 72pt/in

However as far as I know SumatraPDF expects either 72pt or 96dpi as defaults

**Comment by GitHubRulesOK** [comment] 2020-02-16 01:11
@nod5 
OK that works alright in bottom right of page will see if I can find a giant file but it may take some time to trawl archives

re: dots on previous page
<strike>when in scroll mode I can be zoomed in to bottom of current page so NO way previous page could be referenced however a dot that's visibly misplaced will still appear on the page before, I also guess erase is atempting to clear previous page objects but have not tested for that</strike>

Ok I seem to perhaps got that wrong as I can find them on the page after which is consistent with messing backwards and forwards between pages in scroll mode

**Comment by GitHubRulesOK** [comment] 2020-02-16 01:34
I guess within current constraints this issue is resolved as well as possible for my complaint
 perhaps close and let others with any similar issue going forward open as fresh Issue.

**Comment by nod5** [comment] 2020-02-16 01:42
> OK that works alright in bottom right of page will see if I can find a giant file 

Ok good. 

> I guess within current constraints this issue is resolved as well as possible for my complaint
perhaps close and let others with any similar issue going forward open as fresh Issue.

I'll leave it open a bit in case other related feedback comes in and in case you find some giant sized PDF that the test code cannot handle. I also need to check SumatraPDF C++ source on how the position notification strings are generated, to see what variations in values are possible. For example might some translations come with other separators than  `space` and ` ,` and `.` for large values? 

I appreciate all your tests and feedback, thank you. 👍 

The `Ctrl+PgUp/PgDn` issue you mentioned earlier could be split to its own issue perhaps.

**Comment by GitHubRulesOK** [comment] 2020-02-16 02:09
Ok
I found a large one but not giant (approx 100" = 260 cm wide = 7,440.0 pts) it is slow to handle and I see the refresh symbol for a while but by zooming in I can erase dots in corners on a block of highlight, but the block also gets erased, which is not what I wanted, but it is expected behaviour. I will leave that for others to suggest as a different request, However you may need to warn users that erasing nested highlights will also erase the containing one.

**Comment by nod5** [comment] 2020-02-18 17:33
Bug with reading position from SumatraPDF notification window fixed in master release bb9ea5e
Closing this, open new issues for any remaining separate issues.

**Closed as completed by nod5** 2020-02-18 17:33 UTC
Labels: bug

**Comment by GitHubRulesOK** [comment] 2020-02-19 00:25
Agreed much better all round also have noted

MY  Ctrl+PgUp/PgDn issue  is due to 2 keys for each on this keyboard so the upshot is it works 

However, need to warn users that numpad keys such as 7=Home  1=End 9=PageUp 3-PgDn or any other similar combinations may not work the same as dedicated Home End PgUp PgDn

& if the keypad is compact the pairs may even share only 2 keys but mapped by a function key

**Comment by nod5** [comment] 2020-02-19 16:06
> warn users that numpad keys such as 7=Home 1=End 9=PageUp 3-PgDn or any other similar combinations may not work

Added `^NumpadPgUp` and similar shortcuts in new version, 2680060
